<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonalAiAssistant.AgentTool.Calculator\PersonalAiAssistant.AgentTool.Calculator.csproj" />
    <ProjectReference Include="..\PersonalAiAssistant.AgentTool.ReadFile\PersonalAiAssistant.AgentTool.ReadFile.csproj" />
    <ProjectReference Include="..\PersonalAiAssistant.AgentTool.SolutionAnalyzer\PersonalAiAssistant.AgentTool.SolutionAnalyzer.csproj" />
    <ProjectReference Include="..\PersonalAiAssistant.AgentTool.Sql\PersonalAiAssistant.AgentTool.Sql.csproj" />
    <ProjectReference Include="..\PersonalAiAssistant.AgentTool.Weather\PersonalAiAssistant.AgentTool.Weather.csproj" />
    <ProjectReference Include="..\PersonalAiAssistant.AgentTool\PersonalAiAssistant.AgentTool.csproj" />
    <ProjectReference Include="..\PersonalAiAssistant.Contracts\PersonalAiAssistant.Contracts.csproj" />
    <ProjectReference Include="..\PersonalAiAssistant.Infrastructure\PersonalAiAssistant.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Prompts\PlannerSystem.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Prompts\PlannerSystemExamples.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Prompts\Rag.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
